#!/bin/bash
set -e
echo "Deleting all demoapp/app images..."
docker image rmi demoapp/app:base-build || true
docker image rmi demoapp/app:current-build || true
docker image rmi demoapp/app:latest-build || true
docker image rmi demoapp/app:current || true
docker image rmi demoapp/app:latest || true
